name: CI
on: ["push", "pull_request"]

env:
  MORALIS_KEY: ${{ secrets.MORALIS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "17.4.0"

      - name: Install Packages
        uses: borales/actions-yarn@master
        with:
          cmd: install

      - name: Run Lint
        uses: contractshark/inject-solhint-ci@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          solhint_input: 'contracts/*.sol'

      - name: Run Tests
        uses: borales/actions-yarn@master
        with:
          cmd: coverage 
            
      - name: Codecov
        uses: codecov/codecov-action@master
        with:
          verbose: true 

