name: CI
on: ["push", "pull_request"]

env:
  MORALIS_KEY: ${{ secrets.MORALIS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "17.4.0"

      - name: install packages
        uses: borales/actions-yarn@master
        with:
          cmd: install

      - name: Run Tests
        uses: borales/actions-yarn@master
        with:
          cmd: coverage 
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finish
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          parallel-finished: true

