name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install -g yarn ganache-cli
      - run: yarn
      - run: ./mainnet-ganache
      - run: truffle test

